name: '"Modulemancer registry login" Action For GitHub Actions'
description: 'Configure credentials for Modulemancer automagically.'
branding:
  icon: 'cloud'
  color: 'green'
runs:
  using: 'node16'
  main: 'src/index.js'
