name: 'Modulemancer registry login'
description: 'Configure Terraform credentials for Modulemancer automagically.'
branding:
  icon: 'cloud'
  color: 'green'
runs:
  using: 'node16'
  main: 'src/index.js'
